version: 0.2

phases:
  install:
    runtime-versions:
      git: 2.x
    commands:
      - echo "Fetching SSH private key from Parameter Store..."
      - mkdir -p ~/.ssh

      # Retrieve and decode the key
      aws ssm get-parameter --name "$PARAM_NAME" --with-decryption --query "Parameter.Value" --output text > ~/.ssh/id_rsa

      # Set permissions
      - chmod 600 ~/.ssh/id_rsa

      # SSH config
      - echo "Host git-codecommit.*.amazonaws.com" > ~/.ssh/config
      - echo "  User APKAXXXXXXX" >> ~/.ssh/config      # Replace with your IAM SSH Key ID
      - echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
      - echo "  StrictHostKeyChecking no" >> ~/.ssh/config
      - chmod 600 ~/.ssh/config

      # Start SSH agent and add key
      - eval "$(ssh-agent -s)"
      - ssh-add ~/.ssh/id_rsa

  build:
    commands:
      - echo "Testing SSH connection..."
      - ssh -v git-codecommit.us-east-1.amazonaws.com || true
      - echo "Cloning CodeCommit repo via SSH..."
      - git clone ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/another-repo
